from agent.triage import is_fixable
from agent.planner import create_plan
from agent.file_finder import find_files

from core.repo_manager import get_repo_tree
from core.safe_editor import apply_safe_fix
from core.git_ops import create_branch, commit_all, push_branch

from agent.pr_agent import create_pr

import subprocess
import datetime
import sys

REPO_NAME = "macrahul/autonomous-ai-bugfixer"

# ---------------------------
# 1. Read production error
# ---------------------------
with open("inputs/prod_error.log") as f:
    error_log = f.read()

# ---------------------------
# 2. Triage
# ---------------------------
if not is_fixable(error_log):
    sys.exit("Not fixable by AI")

# ---------------------------
# 3. Planning
# ---------------------------
plan = create_plan(error_log)
print("✅ PLAN:", plan)

# ---------------------------
# 4. Repo context
# ---------------------------
repo_tree = get_repo_tree(REPO_NAME)
files = find_files(error_log, repo_tree)

valid_files = []
for file in files:
    if file.endswith(".py"):
        if file.startswith("repo_clone/"):
            valid_files.append(file.replace("repo_clone/", ""))
        else:
            valid_files.append(file)

print("✅ VALID FILES:", valid_files)

if not valid_files:
    sys.exit("No valid files found to fix")

# ---------------------------
# 5. CREATE BRANCH FIRST ✅✅
# ---------------------------
branch = f"ai-fix-{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"
print("🌿 CREATING BRANCH:", branch)
create_branch(branch)

# ---------------------------
# 6. Apply fix + verify
# ---------------------------
for file in valid_files:
    local_path = f"repo_clone/{file}"

    print("✅ OPENING FILE:", local_path)

    print("🛠️ APPLYING SAFE FIX...")
    success = apply_safe_fix(local_path)
    if not success:
        sys.exit("Safe fix application failed")

    print("✅ SAFE FIX APPLIED")

    # Verification
    print("🔍 VERIFYING FIX...")
    result = subprocess.run(
        ["python", local_path],
        capture_output=True,
        text=True
    )

    print("STDOUT:", result.stdout)
    print("STDERR:", result.stderr)

    if result.returncode != 0:
        sys.exit("❌ Verification failed")

    print("✅ VERIFICATION PASSED")

# ---------------------------
# 7. Commit & push
# ---------------------------
print("📦 COMMITTING FIX")
commit_all("Autonomous AI: fix production error")

print("🚀 PUSHING BRANCH")
push_branch(branch)

# ---------------------------
# 8. Create PR
# ---------------------------
print("🔀 CREATING PR")
create_pr(
    repo_name=REPO_NAME,
    branch=branch,
    title="Autonomous AI Fix: Production Error",
    body=f"""
### 🤖 Autonomous AI Fix

**Detected From**
Production error logs

**Plan**
{plan}

**Verification**
✅ Local execution passed
✅ No runtime exception

**Generated By**
Autonomous AI Agent
"""
)

print("✅ AUTONOMOUS FIX FLOW COMPLETED")