from agent.triage import is_fixable
from agent.planner import create_plan
from agent.file_finder import find_files
from agent.registry import select_executor
from agent.reflection import should_retry

from core.repo_manager import get_repo_tree
from core.git_ops import create_branch, commit_all, push_branch
from agent.pr_agent import create_pr

import subprocess
import datetime
import sys

REPO_NAME = "macrahul/autonomous-ai-bugfixer"
MAX_RETRIES = 1

# ---------------------------
# 1. Read production error
# ---------------------------
with open("inputs/prod_error.log") as f:
    error_log = f.read()

# ---------------------------
# 2. Triage
# ---------------------------
if not is_fixable(error_log):
    sys.exit("Not fixable by AI")

# ---------------------------
# 3. Planning
# ---------------------------
plan = create_plan(error_log)
print("✅ PLAN:", plan)

# ---------------------------
# 4. Repo context
# ---------------------------
repo_tree = get_repo_tree(REPO_NAME)
files = find_files(error_log, repo_tree)

valid_files = []
for file in files:
    if file.endswith(".py"):
        if file.startswith("repo_clone/"):
            valid_files.append(file.replace("repo_clone/", ""))
        else:
            valid_files.append(file)

print("✅ VALID FILES:", valid_files)

if not valid_files:
    sys.exit("No valid files found to fix")

# ---------------------------
# 5. Apply fix with retry
# ---------------------------
fix_applied = False

for file in valid_files:
    local_path = f"repo_clone/{file}"
    print("✅ OPENING FILE:", local_path)

    attempt = 0

    while True:
        executor = select_executor(error_log)

        if executor:
            print(f"🧠 Selected Executor: {executor.name()}")
            applied = executor.apply_fix(local_path)
        else:
            print("❌ No executor found for this error.")
            sys.exit(1)

        if applied:
            fix_applied = True
            print("✅ SAFE FIX APPLIED")
        else:
            print("ℹ️ No fix needed or already present")

        # Verification
        print("🔍 VERIFYING FIX...")
        result = subprocess.run(
            ["python", local_path],
            capture_output=True,
            text=True
        )

        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)

        if result.returncode == 0:
            print("✅ VERIFICATION PASSED")
            break  # ✅ Success

        attempt += 1

        if not should_retry(attempt, MAX_RETRIES):  # [2]
            sys.exit("❌ Fix failed after retries")

        print("🔁 Retrying fix attempt...")

# ---------------------------
# 6. NO-OP EXIT
# ---------------------------
if not fix_applied:
    print("ℹ️ No fixes were applied. Skipping branch/commit/PR.")
    print("✅ AUTONOMOUS FIX FLOW COMPLETED (NO-OP)")
    sys.exit(0)

# ---------------------------
# 7. Create branch
# ---------------------------
branch = f"ai-fix-{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"
print("🌿 CREATING BRANCH:", branch)
create_branch(branch)

# ---------------------------
# 8. Commit & push
# ---------------------------
print("📦 COMMITTING FIX")
committed = commit_all("Autonomous AI: fix production error")

if not committed:
    print("ℹ️ No changes to commit. Skipping push & PR.")
    sys.exit(0)

print("🚀 PUSHING BRANCH")
push_branch(branch)

# ---------------------------
# 9. Create PR
# ---------------------------
print("🔀 CREATING PR")
create_pr(
    repo_name=REPO_NAME,
    branch=branch,
    title="Autonomous AI Fix: Production Error",
    body=f"""
### 🤖 Autonomous AI Fix

**Detected From**
Production error logs

**Plan**
{plan}

**Verification**
✅ Local execution passed
✅ No runtime exception

**Generated By**
Autonomous AI Agent
"""
)

print("✅ AUTONOMOUS FIX FLOW COMPLETED")